version: "3.8"
services:
  database:
      image: mcr.microsoft.com/mssql/server:2019-latest
      environment:
        - SA_PASSWORD=1Secure*Password1
        - ACCEPT_EULA=Y
      ports:
        - '1433:1433'
  backend: 
    build: .\Backend
    container_name: backend
    ports: 
      - '7196:80'
  frontend:
    build: .\AngularFrontend
    container_name: frontend
    ports:
      - '4200:8080'
  
    